### ISSUE TITLE
Cant update config

### ISSUE THREAD

**Issue by nicolatamburini** [antonk52/lilconfig#28]
I'm trying to load a config.js two times, but the second time seems to be ignored and i still see the first one.

I have a working example here: 
https://stackblitz.com/edit/node-txq8a4?file=index.js

just run this command:
```
npm run test
```

where am i wrong?

**Comment by vitto** [comment]
the problem seems to be related to the `require` method:
https://bambielli.com/til/2017-04-30-node-require-cache/

**Comment by nicolatamburini** [comment]
i resolved the issue adding 
```
delete require.cache[path.resolve(configPath)];
```
before the second time i call lilconfig
