### ISSUE TITLE
AsyncSearcher Type

### ISSUE THREAD

**Issue by tyrellbain** [antonk52/lilconfig#32]
Hi,

I'm creating a typescript class and trying to type one of the properties as `AsyncSearcher` but it isn't an exported type. How should I correctly be typing a property that will hold the return of `lilconfig('my_module')`?

Example:
```
class MyClass {
  configSearcher: AsyncSearcher;

  constructor() {
    this.configSearcher = lilconfig('my_module');
  }
}
```

**Comment by antonk52** [comment]
Hi and thank you for the issue.

The type is not exported as there is no such type exported from cosmiconfig.

However, you can still extract the type via `ReturnType<typeof lilconfig>`

```ts
import {lilconfig, lilconfigSync} from 'lilconfig'

declare function takesSearcher(searcher: ReturnType<typeof lilconfig>): void

const asyncSearcher = lilconfig('foo');

takesSearcher(asyncSearcher) // no error

takesSearcher({}) // expected error

const syncSearcher = lilconfigSync('foo');

takesSearcher(syncSearcher) // expected error
```

[ts playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwDbCQYwgOwGbAOYA0cK6WueAygJ6ZoC+c2UEIcA5CRjvmwFC8ATAKZokAQyhDGAV1oxgWODDEBrIQGcKQiWgAWQqAAp12qHoMAuOACUhMaVEwAVKmCEAeGK6ERsxVFzkAHwAlFYAbhDAAvxc6vBi6jRoWjr6UHAAvP6k3HiGbNgQEGwhANz8ymqapuZGicmpZukhcAD0bXCYEHAGzFCVqhpNdYYIdK0dvQAebmgwQgK9UP2xWPFwSbQj6Vk5gfjUtAVFJeWD1TsGxo21Le2dQrMiC0t90EA)

**Comment by tyrellbain** [comment]
@antonk52 That makes sense, thank you!
