### ISSUE TITLE
Q: How to stop searching recursively?

### ISSUE THREAD

**Issue by glensc** [antonk52/lilconfig#36]
See this problem:
- https://github.com/okonet/lint-staged/issues/1243

**Comment by antonk52** [comment]
Hi. You can provide a `stopdir` option that would point to your repository root or some other place that would specify the location where the search would stop. Please see the example in the readme:

https://github.com/antonk52/lilconfig#usage

Alternatively to search you can use `load` method to load a config from a specific path if you know in advance where it should be. For example current repository root. 

Let me know if this helps.

**Comment by antonk52** [comment]
Based on the lint-staged issue linked it looks like the question is unrelated to lilconfig itself. I am going to close this issue. Please comment if you think otherwise.
