### ISSUE TITLE
Css Minimizer plugin TypeError: lilconfigSync is not a function

### ISSUE THREAD

**Issue by ucefkh** [antonk52/lilconfig#40]
Hello lil config,

I have a lil bug here

![image](https://user-images.githubusercontent.com/1968135/227578259-8dcf035b-4503-40ef-b4f9-d8034ef76c8b.png)

thanks

**Comment by antonk52** [comment]
Hi, thanks for the issue.

Can you share some reproduction steps? From the attached image it's pretty difficult to guess what the issue is. A repro example would be great to be able to debug the error.

Thanks

**Comment by ucefkh** [comment]
Hello  its related to this issue!

https://github.com/facebook/create-react-app/issues/13087

you can see the repo there

Thanks

**Comment by antonk52** [comment]
There hasn't been any activity in this issue or the one linked in create react app. I have also responded in the create react app issue. Lets keep the discussion there. For now I do not see the problem to be caused by this package. If this is the case, I am happy to reopen the issue.
