### ISSUE TITLE
feature: support a `startFrom` path specifier

### ISSUE THREAD

**Issue by shellscape** [antonk52/lilconfig#51]
hey there :wave: thanks for putting this package together. I'd like to request a `startFrom` option that specifies a path to begin searching from. I'm writing tests for a package that uses `lilconfig` and the only way I can get those to work is to put the test config fixture files into the project root, which is non-optimal.

**Comment by antonk52** [comment]
Hey, if I understand your feature request correctly the `startFrom` is already supported as a first argument to `search` functions in async and sync versions.

https://github.com/antonk52/lilconfig/blob/master/src/index.js#L167

Can you share more on why exposing it as an option can be beneficial?

**Comment by shellscape** [comment]
Ah yeah it's the same thing. Could definitely do with some documentation in the readme. I typically don't source dive unless there's a problem, and that param didn't register when I was making modifications.
